# Create a service account for GitHub Actions
apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-actions-machineuser
  namespace: dev
  labels:
    # https://helm.sh/docs/chart_best_practices/labels/
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ .Values.appName }}
    app.kubernetes.io/version: {{ .Chart.Version | quote }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}

---

# Create a new role with required permissions to build and deploy
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'cicd-machineuser'
  annotations:
    openshift.io/description: >-
      Grants the right to build, push, pull images and deploy from within a project.
      Used primarily with service accounts from a CI/CD workflow.
  labels:
    # https://helm.sh/docs/chart_best_practices/labels/
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ .Values.appName }}
    app.kubernetes.io/version: {{ .Chart.Version | quote }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
rules:
  - verbs:
      - delete
    apiGroups:
      - ''
    resources:
      - replicationcontrollers
  - verbs:
      - get
      - list
      - update
      - watch
    apiGroups:
      - ''
    resources:
      - replicationcontrollers
  - verbs:
      - get
      - update
    apiGroups:
      - ''
    resources:
      - replicationcontrollers/scale
  - verbs:
      - create
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - pods
  - verbs:
      - get
    apiGroups:
      - ''
    resources:
      - pods/log
  - verbs:
      # - create
      - list
    apiGroups:
      - ''
    resources:
      - events
  - verbs:
      - create
      - update
    apiGroups:
      - image.openshift.io
    resources:
      - imagestreamtags
      - imagetags
  - verbs:
      - get
      - update
    apiGroups:
      - image.openshift.io
    resources:
      - imagestreams/layers
  - verbs:
      - get
      - create
    apiGroups:
      - image.openshift.io
    resources:
      - imagestreams
  - verbs:
      - update
    apiGroups:
      - build.openshift.io
    resources:
      - builds/details
  - verbs:
      - get
    apiGroups:
      - build.openshift.io
    resources:
      - builds
  - verbs:
      - create
    apiGroups:
      - build.openshift.io
    resources:
      - buildconfigs/instantiate

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'cicd-machineusers'
  namespace: dev
  annotations:
    openshift.io/description: >-
      Allows service accounts to build, push, pull images and deploy from within a project.
  labels:
    # https://helm.sh/docs/chart_best_practices/labels/
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ .Values.appName }}
    app.kubernetes.io/version: {{ .Chart.Version | quote }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
subjects:
  - kind: ServiceAccount
    name: github-actions-machineuser
    namespace: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: 'cicd-machineuser'



