# BuildConfig for spring-boot-dummy application using Source-to-Image (S2I)
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: {{ .Values.appName }}
    # https://helm.sh/docs/chart_best_practices/labels/
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ .Values.appName }}
    app.kubernetes.io/version: {{ .Chart.Version | quote }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  name: {{ .Values.appName }}
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: {{ .Values.appName }}:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/mpbauer-playground/spring-boot-dummy
    type: Git
    sourceSecret:
      name: {{ .Values.githubPullSecretName }}
  strategy:
    sourceStrategy:
      from:
        kind: DockerImage
        name: registry.redhat.io/ubi8/openjdk-11:latest
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
    - type: ConfigChange
    - type: ImageChange

---
# Create ImageStream for spring-boot-dummy docker images
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: {{ .Values.appName }}
  labels:
    build: {{ .Values.appName }}
    # https://helm.sh/docs/chart_best_practices/labels/
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ .Values.appName }}
    app.kubernetes.io/version: {{ .Chart.Version | quote }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}