apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  labels:
    # https://helm.sh/docs/chart_best_practices/labels/
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ .Values.appName }}
    app.kubernetes.io/version: {{ .Chart.Version | quote }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  selector:
    deploymentConfig: {{ .Values.appName }}
  ports:
    - name: service
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: actuator
      port: 8081
      protocol: TCP
      targetPort: 8081
  sessionAffinity: None
  type: ClusterIP
