name: Manual Deployment
on:
  workflow_dispatch:
    inputs:
      stage:
        description: 'Stage to deploy (preprod | prod):'
        required: true
        default: 'preprod'
      version:
        description: 'Version (e.g. "1.0.1")'
        required: true
        default: 'x.x.x'
jobs:
  preprod-deployment:
    name: 'Deploy to PREPROD'
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.stage == 'preprod'}}
    steps:
      - name: 'Deploy to PREPROD'
        run: echo "Deploying app with version '${{ github.event.inputs.version }}' to '${{ github.event.inputs.stage }}' ..."

  prod-deployment:
    name: 'Deploy to PROD'
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.stage == 'prod'}}
    steps:
      - name: 'Deploy to PROD'
        run: echo "Deploying app with version '${{ github.event.inputs.version }}' to '${{ github.event.inputs.stage }}' ..."
